local M = {}

function M:setup()
    local project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ":p:h:t")
    local workspace_dir = vim.fn.stdpath("data") .. package.config:sub(1, 1) .. "jdtls-workspace" .. package.config:sub(1, 1) .. project_name

    local root_dir

    -- Check if the current directory is a Hybris project
    if project_name == "hybris" and
        vim.fn.isdirectory("hybris/bin/platform") ~= 0 and
        vim.fn.isdirectory("hybris/bin/custom") ~= 0 then

        -- For Hybris projects, the root is the 'platform' directory.
        root_dir = vim.fn.getcwd() .. package.config:sub(1, 1) .. "hybris" .. package.config:sub(1, 1) .. "bin" .. package.config:sub(1, 1) .. "platform"

        -- For Hybris, we need to find all custom extensions to add them to the workspace.
        -- JDTLS will automatically pick up .project and .classpath files if they exist in these directories.
        -- The actual classpath and project file generation is handled by 'ant' outside of Neovim.
        -- We simply need to tell JDTLS where to look for source folders and dependencies.
        -- JDTLS typically works by identifying root directories containing .project files.
        -- For a multi-module project like Hybris, each extension that has a .project file
        -- will be recognized as a separate project within the workspace.
        -- We don't need to manually construct the classpath here; JDTLS handles this
        -- if the .project and .classpath files are correctly generated by 'ant'.

        -- You might need to adjust the settings or init_options if JDTLS doesn't
        -- automatically discover all extensions. A common approach is to point
        -- `bundles` to any custom plugins or add additional `java.project.referencedPaths`
        -- if direct paths to compiled jars are needed, but JDTLS is generally good
        -- at finding projects based on .project files.

        -- Example of potentially adding referenced paths if needed (uncomment and modify)
        -- local custom_extensions_path = vim.fn.getcwd() .. package.config:sub(1, 1) .. "hybris" .. package.config:sub(1, 1) .. "bin" .. package.config:sub(1, 1) .. "custom"
        -- local custom_extensions = vim.fn.glob(custom_extensions_path .. "/*", 0, 1)
        -- local referenced_paths = {}
        -- for _, ext_path in ipairs(custom_extensions) do
        --     if vim.fn.isdirectory(ext_path) ~= 0 then
        --         table.insert(referenced_paths, ext_path .. "/bin/*.jar") -- Example for compiled jars
        --         table.insert(referenced_paths, ext_path .. "/src")      -- Example for source folders
        --     end
        -- end
        -- config.settings.java.project.referencedPaths = referenced_paths

    else
        -- Fallback to the current logic for other Java projects
        root_dir = require("jdtls.setup").find_root({ ".git", "mvnw", "gradlew" })
    end

    local config = {
        cmd = {
            "/Users/manolo/.sdkman/candidates/java/current/bin/java",
            "-Declipse.application=org.eclipse.jdt.ls.core.id1",
            "-Dosgi.bundles.defaultStartLevel=4",
            "-Declipse.product=org.eclipse.jdt.ls.core.product",
            "-Dlog.protocol=true",
            "-Dlog.level=ALL",
            "-Xmx1g",
            "--add-modules=ALL-SYSTEM",
            "--add-opens",
            "java.base/java.util=ALL-UNNAMED",
            "--add-opens",
            "java.base/java.lang=ALL-UNNAMED",
            "-jar",
            vim.fn.stdpath("data") .. package.config:sub(1, 1) .. "mason" .. package.config:sub(1, 1) .. "packages" .. package.config:sub(1, 1) .. "jdtls" .. package.config:sub(1, 1) .. "plugins" .. package.config:sub(1, 1) .. "org.eclipse.equinox.launcher_1.7.0.v20250519-0528.jar",
            "-configuration",
            vim.fn.stdpath("data") .. package.config:sub(1, 1) .. "mason" .. package.config:sub(1, 1) .. "packages" .. package.config:sub(1, 1) .. "jdtls" .. package.config:sub(1, 1) .. "config_" .. "mac_arm",
            "-data",
            workspace_dir,
        },
        root_dir = root_dir, -- Set the determined root_dir here
        settings = {
            java = {},
        },
        init_options = {
            bundles = {},
        },
    }
    require("jdtls").start_or_attach(config)
end

return M
